USER_STATUS_ACTIVE = "active"
USER_STATUS_SUSPENDED = "suspended"
USER_STATUS_DELETED = "deleted"

AUTH_SESSION_ACTIVE = "active"
AUTH_SESSION_REVOKED = "revoked"
AUTH_SESSION_EXPIRED = "expired"

SUBSCRIPTION_ACTIVE = "active"
SUBSCRIPTION_TRIALING = "trialing"
SUBSCRIPTION_PAST_DUE = "past_due"
SUBSCRIPTION_CANCELED = "canceled"
SUBSCRIPTION_EXPIRED = "expired"

PAYMENT_PROVIDER_BEPUSDT = "bepusdt"
PAYMENT_STATUS_PENDING = "pending"
PAYMENT_STATUS_PAID = "paid"
PAYMENT_STATUS_EXPIRED = "expired"
PAYMENT_STATUS_CANCELED = "canceled"
PAYMENT_STATUS_FAILED = "failed"

MODEL_NODE_HEALTHY = "healthy"
MODEL_NODE_DEGRADED = "degraded"
MODEL_NODE_UNHEALTHY = "unhealthy"
MODEL_NODE_DRAINING = "draining"

PROVIDER_TYPE_OPENAI_COMPAT = "openai_compat"

MESSAGE_ROLE_SYSTEM = "system"
MESSAGE_ROLE_USER = "user"
MESSAGE_ROLE_ASSISTANT = "assistant"
MESSAGE_ROLE_TOOL = "tool"

MESSAGE_STATUS_PENDING = "pending"
MESSAGE_STATUS_STREAMING = "streaming"
MESSAGE_STATUS_COMPLETED = "completed"
MESSAGE_STATUS_FAILED = "failed"
MESSAGE_STATUS_CANCELED = "canceled"
